### PR TITLE
Fixes #352 - Bubble worker HTTP server start errors.

### LINKED ISSUE #352: Worker does not bubble HTTP server start errors
Currently, if the Promise starting the HTTP Server rejects, the error results in an uncaught promise exception. I have a fix for this and will put it up momentarily.

### PR DESCRIPTION
**Pull request by austinkelleher**
Fixes #352 an unhandled promise rejection error.

### CODE REVIEW

**Comment by jondubois** [comment]
@austinkelleher my mistake, nicely caught! (pun intended).

At a glance both of your PRs look very good.
I'll merge and push/publish the fix later today.

File: scworker.js [hunk 1]
```diff
@@ -134,8 +134,9 @@ SCWorker.prototype._init = function (options) {
   }
 
   this.on(this.EVENT_READY, function () {
-    self.start();
-    handleReady();
+    self.start().then(function () {
+      handleReady();
```
Comment (austinkelleher) [inline scworker.js]: Also I changed this block of code to only execute `handleReady` if the `start` function properly resolves.
